### ISSUE TITLE
<PC 1.20.1 Forge custom modpack> most likely an incompatibility issue, crash on startup

### ISSUE THREAD

**Issue by NotYourLifeline** [TunefulTurnip/Deep-Aether#211]
### Forge/Neoforge Version

47.3.0

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.5.1

### Log Files

[latest.log](https://github.com/user-attachments/files/18054141/latest.log)

[crash-2024-12-09_06.53.02-client.txt](https://github.com/user-attachments/files/18054144/crash-2024-12-09_06.53.02-client.txt)

### Bug Report

other Aether addons(Lost Content, Redux, Farmer's Delight addon) work just fine with each other, but It's just the Deep Aether that's causing the crash when enabled.

modlist:
![2024-12-09_06 49 26](https://github.com/user-attachments/assets/747650f9-182d-46e3-af50-9a5a9b4db64c)
![2024-12-09_06 49 33](https://github.com/user-attachments/assets/7fd84f38-7099-49b6-95d2-cbb3cdca1071)

**Comment by TunefulTurnip** [comment]
This appears to be an issue between Aether Redux and Optifine and not Deep Aether; Generally it's not recommended to use Optifine together with mods since it's closed source and is known to cause issues with other mods due to how it operates. Use alternative mods instead if it's performance you are after, such as Embeddium and Oculus if you want shaders.
